// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDurdAyQjD1yTaAVskxY8Koo1qF2Axn1uo",
      authDomain: "jolii-me.firebaseapp.com",
      databaseURL: "https://jolii-me.firebaseio.com",
      projectId: "jolii-me",
      storageBucket: "jolii-me.appspot.com",
      messagingSenderId: "961419777800",
      appId: "1:961419777800:web:0c5c5d90027999b9507ebd",
      measurementId: "G-DG3CRLDNYV");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxvvDeyhm02gd1mxQhOuW-bakrgNki2k',
    appId: '1:961419777800:android:67ea7a995d144d74507ebd',
    messagingSenderId: '961419777800',
    projectId: 'jolii-me',
    databaseURL: 'https://jolii-me.firebaseio.com',
    storageBucket: 'jolii-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIhW-KL9hnJdObJG-Noq66PCVkXu2uA4',
    appId: '1:961419777800:ios:e0024bf5e3bf2658507ebd',
    messagingSenderId: '961419777800',
    projectId: 'jolii-me',
    databaseURL: 'https://jolii-me.firebaseio.com',
    storageBucket: 'jolii-me.appspot.com',
    androidClientId:
        '961419777800-45o0fugs52bob8j6q6uhfrcevlg9qg2h.apps.googleusercontent.com',
    iosClientId:
        '961419777800-9pufs3psehmdsg03ebd6d1qphkf0sm05.apps.googleusercontent.com',
    iosBundleId: 'com.appfliiq.jolii',
  );
}
